name: Build
on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string

jobs:
  build:
    runs-on: big-runner-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build containers
        run: docker compose build --progress=plain
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          ORG: jitolabs
          TAG: ${{ inputs.TAG }}
